config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: :destroy
  resources :movies, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true,
                    uniqueness: true
  validates :overview, presence: true
  validates :rating, numericality: { allow_nil: true, greater_than_or_equal_to: 0,
                                     less_than_or_equal_to: 10 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    # raise
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  def bookmark_params
    params[:bookmark][:list_id] = params[:list_id]
    params.require(:bookmark).permit(:movie_id, :list_id, :comment)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all.limit(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Bookmarks#new</h1>
<%= simple_form_for [@list, @bookmark], url: list_bookmarks_path do |f| %>
  <%= f.association :movie, collection: Movie.order(:title) %>
  <%= f.input :comment %>
  <%= f.submit class: 'mt-2' %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <i class="fas fa-film"></i>
      <%# <img src="https://media.istockphoto.com/photos/movie-popcorn-box-fresh-snack-food-container-isolated-on-white-picture-id172851244?k=20&m=172851244&s=612x612&w=0&h=C60587sjxcpWeRAJL_zhrsHHZXZdThENRa-aFxDCGa8=" /> %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%# <h2>Arthur's cinema</h2> %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <%= link_to "Create a new list", new_list_path, class: "btn btn-primary" %>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
      <%= yield %>
  </body>

</html>

app/views/lists/_banner.html.erb
<div class="banner"
  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @list.photo.attached? ? cl_image_path(@list.photo.key) : @list.movies.order(rating: :desc).first.poster_url%>">
  <div class="container">
    <h1><%= @list.name %></h1>
    <div class="banner-btn"><%= link_to "Add a movie", new_list_bookmark_path(@list), class: "btn btn-primary" %></div>

  </div>
</div>

app/views/lists/_card-category.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
  <%= list.name %>
</div>

app/views/lists/_card-movie.html.erb
<% trash_can = sanitize "<i class='far fa-trash-alt'></i>" %>
<div class="card-movie">
  <div class="card-movie-front">
    <img src=<%= movie.poster_url %> />
    <div class="card-movie-rating">
      <p><strong><%= movie.rating %></strong></p>
    </div>
  </div>

  <div class="card-movie-infos">
    <div class="d-flex justify-content-between">
      <h2><%= movie.title %></h2>
      <div class="card-movie-rating">
        <p><strong><%= movie.rating %></strong></p>
      </div>
      <!--
      <h2><%#= link_to trash_can, bookmark_path(@list.bookmarks[ind]), method: :delete %></h2>
      -->
    </div>
    <p><%= movie.overview %></p>
  </div>
</div>

app/views/lists/_card.html.erb
<% trash_can = sanitize "<i class='far fa-trash-alt'></i>" %>
<div class="card-movie">
  <div class="card-movie-front">
    <img src=<%= movie.poster_url %> />
    <div class="card-movie-rating">
      <p><strong><%= movie.rating %></strong></p>
    </div>
  </div>

  <div class="card-movie-infos">
    <div class="d-flex justify-content-between">
      <h2><%= movie.title %></h2>
      <div class="card-movie-rating">
        <p><strong><%= movie.rating %></strong></p>
      </div>
      <!--
      <h2><%= link_to trash_can, bookmark_path(@list.bookmarks[ind]), method: :delete %></h2>
      -->
    </div>
    <p><%= movie.overview %></p>
  </div>
</div>

app/views/lists/index.html.erb
<h1>Lists</h1>
<div class="container mt-4">
  <% @lists.each do |list| %>
    <div class="list-container">
      <div class="list-name">
        <h2><%= list.name %></h2>
        <p><%= "explore all" %> <i class="fas fa-angle-right"></i></p>
        <%= link_to "", list_path(list) %>
      </div>
      <div class="cards-line">
        <% list.movies.order(rating: :desc).limit(5).each do |movie| %>
          <%= render "card-movie", movie: movie %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "mt-2" %>
<% end %>

app/views/lists/show.html.erb
<%= render "banner" %>
<div class="container mt-4">
  <div class="cards">
    <% @list.movies.order(rating: :desc).each do |movie| %>
      <%= render "card-movie", movie: movie %>
    <% end %>
  </div>
</div>

app/views/movies/_card.html.erb
<div class="card-trip">
  <img src=<%= movie.poster_url %> />
  <div class="card-trip-infos">
    <div>
      <h2><%= movie.title %></h2>
      <%# <p>Short description here!</p> %>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<h1>Movies#index</h1>

<div class="cards">
  <% @movies.each do |movie| %>
  <%= render "card", movie: movie, display_delete_btn: false %>
  <% end %>
</div>